rvm:
    - 2.2.2

cache: bundler

before_script:
	- brew install phantomjs

addons:
    firefox: "49.0"
    code_climate:
        repo_token: 5b48a2bbbf03e9c87588768a9041958f465d83df080d1ad88384e363b5497b1b
